---
- hosts: all
  user: root
  tasks:
    - name: install apache
      apt:
        name:
          - apache2
          - apache2-bin
          - apache2-data
          - apache2-utils
          - libapache2-mod-php8.1
        state: present
        update_cache: true

    - name: configure vhosts
      synchronize:
        src: /home/private/School/Fase2/Server & System Management/ansible/apache2/
        dest: /etc/apache2
        delete: true
        rsync_opts:
          - "--chown=root:root"

    - name: add pages
      synchronize:
        src: /home/private/School/Fase2/Server & System Management/ansible/www/
        dest: /var/www
        delete: true
        rsync_opts:
          - "--chown=root:root"

    - name: restart apache
      service:
        name: apache2
        state: restarted
