- hosts: all
  user: root
  vars:
    domain: lucasov.com
    admin_email: sudo@lucasov.com
  tasks:
    - name: clone repo
      git:
        repo: https://github.com/LucasDaniOV/lucasov.com.git
        dest: "/var/www/{{ domain }}"
        version: main

    - name: create vhost
      file:
        path: "/etc/apache2/sites-available/{{ domain }}.conf"
        state: touch
        mode: 0644
        owner: root
        group: root

    - name: add vhost config
      blockinfile:
        path: "/etc/apache2/sites-available/{{ domain }}.conf"
        block: |
          <VirtualHost *:80>
            ServerName {{ domain }}
            ServerAdmin {{ admin_email }}
            ServerAlias www.{{ domain }}
            DocumentRoot /var/www/{{ domain }}
            ErrorLog ${APACHE_LOG_DIR}/{{ domain }}-error.log
            CustomLog ${APACHE_LOG_DIR}/{{ domain }}-access.log combined
            Redirect permanent / https://{{ domain }}/
          </VirtualHost>
          <VirtualHost *:443>
            ServerName {{ domain }}
            ServerAdmin {{ admin_email }}
            ServerAlias www.{{ domain }}
            DocumentRoot /var/www/{{ domain }}
            ErrorLog ${APACHE_LOG_DIR}/{{ domain }}-error.log
            CustomLog ${APACHE_LOG_DIR}/{{ domain }}-access.log combined
            SSLEngine on
            SSLCertificateFile /etc/ssl/{{ domain }}/cert.pem
            SSLCertificateKeyFile /etc/ssl/{{ domain }}/key.pem
            SSLCertificateChainFile /etc/ssl/{{ domain }}/fullchain.pem
            Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains"
          </VirtualHost>

    - name: enable vhost
      command: a2ensite {{ domain }}.conf
      register: result
      changed_when: result.rc == 0

    - name: restart apache
      service:
        name: apache2
        state: restarted
