- hosts: all
  user: root
  tasks:

  - name: stop apache
    service:
      name: apache2
      state: stopped

  - name: uninstall apache
    apt:
      name:
        - apache2
        - apache2-bin
        - apache2-data
        - apache2-utils
        - libapache2-mod-php8.1
      state: absent
      purge: yes
      autoremove: yes
      autoclean: yes

  - name: remove vhosts
    file:
      path: /etc/apache2
      state: absent

  - name: remove pages
    file:
      path: /var/www
      state: absent
